using Lombiq.Tests.UI.AppExtensions.SqlQueryMonitoring;
using Lombiq.Tests.UI.Exceptions;
using Lombiq.Tests.UI.Extensions;
using Lombiq.Tests.UI.Models;
using Shouldly;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;

namespace Lombiq.Tests.UI.Samples.Tests;

// Here we'll see how to detect potentially inefficient SQL query patterns during UI tests. This can help surface
// classic SELECT N+1 issues (the same SQL command running many times with different parameters), unintentional cache
// misses (the same query with the same parameters running repeatedly), and large result sets that should have been
// filtered.
public class SqlQueryMonitoringTests : UITestBase
{
    public SqlQueryMonitoringTests(ITestOutputHelper testOutputHelper)
        : base(testOutputHelper)
    {
    }

    [Fact]
    public Task SqlQueryMonitoringShouldCatchDuplicatesAndLargeResults() =>
        ExecuteTestAfterSetupAsync(
            async context =>
            {
                // This loads the home page by default. We'll assert on the SQL queries generated by that request.
                await context.AssertSqlQueryMonitoringAsync();

                // Navigate to another page and run a custom assertion.
                await context.GoToRelativeUrlAsync("/categories/travel");

                await context.AssertSqlQueryMonitoringAsync(summary =>
                {
                    summary.Executions.ShouldNotBeEmpty("SQL query monitoring should capture at least one command.");

                    // You can apply your own logic to the summary, e.g. allowlist a specific command or collect stats
                    // for reporting.
                    return Task.CompletedTask;
                });
            },
            configuration =>
            {
                // We'll run assertions explicitly in the test so the captured summaries don't get consumed by the
                // automatic on-page-change assertions.
                configuration.SqlQueryMonitoringConfiguration.RunSqlQueryMonitoringAssertionOnAllPageChanges = false;

                // Set thresholds high enough for this sample to pass. Lower these values in your tests to catch
                // potential issues in the app under test.
                // Same command text repeated with any parameters (useful for spotting SELECT N+1 patterns).
                configuration.SqlQueryMonitoringConfiguration.DuplicateCommandThreshold = 30;

                // Same command text repeated with the same parameter values (useful for spotting missing caching).
                configuration.SqlQueryMonitoringConfiguration.DuplicateCommandWithParametersThreshold = 15;

                // Commands returning more rows than expected (useful for spotting missing SQL filtering).
                configuration.SqlQueryMonitoringConfiguration.ResultSetRowCountThreshold = 200;
            });

    // It's useful to demonstrate how SQL monitoring failures get surfaced. Here we use low thresholds and assert that
    // the monitoring throws, so the test itself still passes.
    [Fact]
    public Task SqlQueryMonitoringShouldSurfaceIssues() =>
        ExecuteTestAfterSetupAsync(
            context => Should.ThrowAsync<SqlQueryMonitoringAssertionException>(() => context.AssertSqlQueryMonitoringAsync()),
            configuration =>
            {
                // We'll assert explicitly so the automatic on-page-change assertion doesn't consume the summary.
                configuration.SqlQueryMonitoringConfiguration.RunSqlQueryMonitoringAssertionOnAllPageChanges = false;

                // Set deliberately low thresholds to trigger failures.
                configuration.SqlQueryMonitoringConfiguration.DuplicateCommandThreshold = 1;
                configuration.SqlQueryMonitoringConfiguration.DuplicateCommandWithParametersThreshold = 1;
                configuration.SqlQueryMonitoringConfiguration.ResultSetRowCountThreshold = 1;
            });

    // SQL monitoring is tenant-aware. This test creates a tenant, switches to it, and verifies monitoring still works.
    [Fact]
    public Task SqlQueryMonitoringShouldWorkOnAnotherTenant() =>
        ExecuteTestAfterSetupAsync(
            async context =>
            {
                const string tenantName = "SqlMonitorTest";
                const string tenantUrlPrefix = "sql-monitor-test";
                const string tenantDisplayName = "Lombiq's OSOCE - SQL Monitoring Tenant";
                const string tenantAdminName = "tenantSqlMonitorAdmin";

                await context.SignInDirectlyAsync();
                await context.CreateAndSwitchToTenantAsync(
                    tenantName,
                    tenantUrlPrefix,
                    new OrchardCoreSetupParameters
                    {
                        SiteName = tenantDisplayName,
                        RecipeId = "Lombiq.OSOCE.Tests",
                        TablePrefix = tenantUrlPrefix,
                        UserName = tenantAdminName,
                    });

                await context.GoToRelativeUrlAsync("/");

                context.GetCurrentUri().AbsolutePath.ShouldStartWith($"/{tenantUrlPrefix}");

                await context.AssertSqlQueryMonitoringAsync(summary =>
                {
                    summary.Executions.ShouldNotBeEmpty("SQL query monitoring should capture at least one command.");
                    return Task.CompletedTask;
                });

                context.SwitchCurrentTenantToDefault();
                await context.GoToRelativeUrlAsync("/");

                context.GetCurrentUri().AbsolutePath.ShouldNotStartWith($"/{tenantUrlPrefix}");

                await context.AssertSqlQueryMonitoringAsync(summary =>
                {
                    summary.Executions.ShouldNotBeEmpty("SQL query monitoring should capture at least one command.");
                    return Task.CompletedTask;
                });
            },
            configuration =>
            {
                configuration.SqlQueryMonitoringConfiguration.RunSqlQueryMonitoringAssertionOnAllPageChanges = false;
                configuration.SqlQueryMonitoringConfiguration.DuplicateCommandThreshold = 30;
                configuration.SqlQueryMonitoringConfiguration.DuplicateCommandWithParametersThreshold = 15;
                configuration.SqlQueryMonitoringConfiguration.ResultSetRowCountThreshold = 200;
            });

    // You can tune thresholds per page. Here we tighten them for the categories page while keeping others looser.
    [Fact]
    public Task SqlQueryMonitoringShouldAllowPerPageThresholds() =>
        ExecuteTestAfterSetupAsync(
            async context =>
            {
                await context.GoToRelativeUrlAsync("/categories/travel");
                await context.GoToRelativeUrlAsync("/about");
            },
            configuration =>
                configuration.Events.BeforeNavigation += (_, targetUri) =>
                {
                    var thresholds = configuration.SqlQueryMonitoringConfiguration;

                    if (targetUri.AbsolutePath.Contains("/categories"))
                    {
                        thresholds.DuplicateCommandThreshold = 20;
                        thresholds.DuplicateCommandWithParametersThreshold = 10;
                        thresholds.ResultSetRowCountThreshold = 100;
                    }
                    else
                    {
                        thresholds.DuplicateCommandThreshold = 30;
                        thresholds.DuplicateCommandWithParametersThreshold = 15;
                        thresholds.ResultSetRowCountThreshold = 200;
                    }

                    return Task.CompletedTask;
                });

    // You can also customize which page changes should be monitored by configuring a predicate.
    [Fact]
    public Task SqlQueryMonitoringShouldRespectPageChangeRule()
    {
        var summaries = new List<SqlQueryMonitoringSummary>();

        return ExecuteTestAfterSetupAsync(
            async context =>
            {
                await context.GoToRelativeUrlAsync("/categories/travel");
                await context.GoToRelativeUrlAsync("/about");

                summaries.Count.ShouldBe(1);
                summaries[0].RequestPath.ShouldContain("/categories");
                summaries[0].Executions.ShouldNotBeEmpty(
                    "SQL query monitoring should capture at least one command.");
            },
            configuration =>
            {
                configuration.SqlQueryMonitoringConfiguration.SqlQueryMonitoringAndAssertionOnPageChangeRule =
                    context => context.GetCurrentUri().AbsolutePath.Contains("/categories");
                configuration.SqlQueryMonitoringConfiguration.AssertSqlQueryMonitoringSummaryAsync = summary =>
                {
                    summaries.Add(summary);
                    return Task.CompletedTask;
                };
            });
    }
}

// END OF TRAINING SECTION: SQL query monitoring tests.
// NEXT STATION: Head over to Tests/SqlServerTests.cs.
