taskkill /f /im "dotnet.exe"
taskkill /f /im "chromedriver.exe"
taskkill /f /im "geckodriver.exe"
taskkill /f /im "IEDriverServer.exe"
taskkill /f /im "msedgedriver.exe"
taskkill /f /im "Lombiq.UITestingToolbox.AppUnderTest*"
