<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPublishable>false</IsPublishable>
    <!-- With these the driver exe files will be copied to all projects referencing this project. Otherwise all child
    projects would need to add the packages too. -->
    <PublishChromeDriver>true</PublishChromeDriver>
    <PublishGeckoDriver>true</PublishGeckoDriver>
    <PublishMsEdgeDriver>true</PublishMsEdgeDriver>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../src/Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Library.Sdk/Sdk/Import.props" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.props" Sdk="Lombiq.MSBuild.Library.Sdk" Version="1.0.1-alpha.15.osoe-1208" />

  <PropertyGroup>
    <Title>Lombiq UI Testing Toolbox for Orchard Core</Title>
    <CopyrightYear>2020</CopyrightYear>
    <DescriptionBody>Web UI testing toolbox mostly for Orchard Core applications. Everything you need to do UI testing with Selenium for an Orchard app is here.</DescriptionBody>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Selenium;Atata;Shouldly;xUnit;Axe;AccessibilityTesting;UITesting;Testing;Automation;ZAP;Zed Attack Proxy;Security;Scanning;OWASP</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/UI-Testing-Toolbox</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Update="ui-testing-toolkit.mjs" CopyToOutputDirectory="PreserveNewest" />
    <Content Include=".config\dotnet-tools.json" CopyToOutputDirectory="PreserveNewest" PackageCopyToOutput="true" />
    <Content Include="SampleUploadFiles\*.*" CopyToOutputDirectory="PreserveNewest" PackageCopyToOutput="true" />
    <Content Include="default.htmlvalidate.json" CopyToOutputDirectory="PreserveNewest" PackageCopyToOutput="true" />
    <Content Include="SecurityScanning\AutomationFrameworkPlanFragments\*" CopyToOutputDirectory="PreserveNewest" PackageCopyToOutput="true" />
    <Content Include="SecurityScanning\AutomationFrameworkPlans\*" CopyToOutputDirectory="PreserveNewest" PackageCopyToOutput="true" />
    <Content Include="PermitNoTitleIframes.htmlvalidate.json" CopyToOutputDirectory="PreserveNewest" PackageCopyToOutput="true" />
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" PackageCopyToOutput="true" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Atata" Version="3.9.0" />
    <PackageReference Include="Atata.Bootstrap" Version="3.0.0" />
    <PackageReference Include="Atata.HtmlValidation" Version="3.4.0" />
    <PackageReference Include="Atata.WebDriverExtras" Version="3.6.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
    <PackageReference Include="Ben.Demystifier" Version="0.4.1" />
    <PackageReference Include="Codeuctivity.ImageSharpCompare" Version="4.1.390" />
    <PackageReference Include="Deque.AxeCore.Commons" Version="4.11.3" />
    <PackageReference Include="Deque.AxeCore.Selenium" Version="4.11.3" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" Version="11.0.0-preview.3.26207.106" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.5" />
    <PackageReference Include="Microsoft.Web.LibraryManager.Build" Version="3.0.71" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" Version="10.4.0" />
    <PackageReference Include="Microsoft.SqlServer.DACFx" Version="170.3.93" />
    <PackageReference Include="Microsoft.SqlServer.SqlManagementObjects" Version="181.19.0" />
    <PackageReference Include="Mono.Posix.NETStandard" Version="1.0.0" />
    <PackageReference Include="OrchardCore.ContentFields" Version="3.0.0-preview-19009" />
    <PackageReference Include="OrchardCore.Logging.NLog" Version="3.0.0-preview-19009" />
    <PackageReference Include="OrchardCore.Recipes.Core" Version="3.0.0-preview-19009" />
    <PackageReference Include="OrchardCore.Workflows" Version="3.0.0-preview-19009" />
    <PackageReference Include="Sarif.Sdk" Version="4.6.4" />
    <!-- Referencing a newer version than what Atata uses, but not the latest version. See the comments in
    renovate.json5 for details. -->
    <PackageReference Include="Selenium.WebDriver" Version="4.41.0" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="TWP.Selenium.Axe.Html" Version="1.0.0" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2" />
    <PackageReference Include="YamlDotNet" Version="17.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lombiq.Tests.UI.AppExtensions\Lombiq.Tests.UI.AppExtensions.csproj" />
    <ProjectReference Include="..\Lombiq.Tests.UI.Shortcuts\Lombiq.Tests.UI.Shortcuts.csproj" />
  </ItemGroup>

  <Choose>
    <When Condition="'$(NuGetBuild)' == 'true'">
      <ItemGroup>
        <PackageReference Include="Lombiq.Tests" Version="5.0.1-alpha.0.osoe-925" />
        <PackageReference Include="Lombiq.HelpfulLibraries.Cli" Version="12.6.1-alpha.7.osoe-925" />
        <PackageReference Include="Lombiq.HelpfulLibraries.OrchardCore" Version="12.6.1-alpha.7.osoe-925" />
        <PackageReference Include="Lombiq.HelpfulLibraries.Refit" Version="12.6.1-alpha.7.osoe-925" />
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <ProjectReference Include="..\..\Lombiq.Tests\Lombiq.Tests.csproj" />
        <ProjectReference Include="..\..\..\src\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.Cli\Lombiq.HelpfulLibraries.Cli.csproj" />
        <ProjectReference Include="..\..\..\src\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.OrchardCore\Lombiq.HelpfulLibraries.OrchardCore.csproj" />
        <ProjectReference Include="..\..\..\src\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.Refit\Lombiq.HelpfulLibraries.Refit.csproj" />
      </ItemGroup>
    </Otherwise>
  </Choose>

  <!-- These are necessary for symbols NuGet packaging, otherwise Shouldly would prevent PDBs to be packaged, see:
  https://github.com/NuGet/Home/discussions/11541. -->
  <PropertyGroup Condition="'$(NuGetBuild)' == 'true'">
    <Optimize>true</Optimize>
    <DebugType>portable</DebugType>
    <Deterministic>true</Deterministic>
    <DeterministicSourcePaths>true</DeterministicSourcePaths>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="node_modules\gremlins.js\dist\gremlins.min.js">
      <Link>Resources\gremlins.min.js</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\gremlins-summoning-circle.js" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="PermitNoTitleIframes.htmlvalidate.json" />
    <None Remove="SecurityScanning\AutomationFrameworkPlanFragments\DisplayActiveScanRuleRuntimesScript.yml" />
    <None Remove="SecurityScanning\AutomationFrameworkPlanFragments\RequestorJob.yml" />
    <None Remove="SecurityScanning\AutomationFrameworkPlanFragments\SpiderAjaxJob.yml" />
    <None Remove="SecurityScanning\AutomationFrameworkPlans\Baseline.yml" />
    <None Remove="SecurityScanning\AutomationFrameworkPlans\FullScan.yml" />
    <None Remove="SecurityScanning\AutomationFrameworkPlans\GraphQL.yml" />
    <None Remove="SecurityScanning\AutomationFrameworkPlans\OpenAPI.yml" />
  </ItemGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../src/Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Library.Sdk/Sdk/Import.targets" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.targets" Sdk="Lombiq.MSBuild.Library.Sdk" Version="1.0.1-alpha.15.osoe-1208" />
</Project>
