---
env:
  contexts:
  - name: "Default Context"
    urls:
    - "<start URL>"
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
    sessionManagement:
      method: "cookie"
      parameters: {}
    technology:
      exclude: []
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    scanOnlyInScope: true
    enableTags: false
    disableAllRules: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters:
    queryGenEnabled: true
    maxQueryDepth: 5
    lenientMaxQueryDepthEnabled: true
    maxAdditionalQueryDepth: 5
    maxArgsDepth: 5
    optionalArgsEnabled: true
    argsType: "both"
    querySplitType: "leaf"
    requestMethod: "post_json"
  name: "graphql"
  type: "graphql"
- parameters: {}
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- parameters: {}
  policyDefinition:
    rules: []
  name: "activeScan"
  type: "activeScan"
- parameters:
    reportDir: "/zap/wrk/reports"
    template: "modern"
    theme: "technology"
    reportTitle: "ZAP Scanning Report"
    reportDescription: ""
  risks:
  - "low"
  - "medium"
  - "high"
  confidences:
  - "low"
  - "medium"
  - "high"
  - "confirmed"
  sections:
  - "passingrules"
  - "instancecount"
  - "alertdetails"
  - "alertcount"
  - "params"
  - "chart"
  - "statistics"
  name: "report"
  type: "report"
