<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPublishable>false</IsPublishable>
    <ImportLombiqHelpfulLibrariesOrchardCore>true</ImportLombiqHelpfulLibrariesOrchardCore>
    <ImportLombiqHelpfulLibrariesLinqToDb>true</ImportLombiqHelpfulLibrariesLinqToDb>
  </PropertyGroup>

  <Import Project="..\..\..\src\Utilities\Lombiq.MSBuild.Targets\Lombiq.MSBuild.Core.Targets\Lombiq.MSBuild.Core.Targets.props"
          Condition="'$(NuGetBuild)' != 'true'"/>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.MSBuild.Core.Targets" Version="1.0.0-alpha.2.nest-643" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Title>Lombiq UI Testing Toolbox - App Extensions</Title>
    <Copyright>Copyright © 2020, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq UI Testing Toolbox - App Extensions: UI testing-related configuration extensions for the web app under test. See the project website for detailed documentation.</Description>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Selenium;Atata;Shouldly;xUnit;Axe;AccessibilityTesting;UITesting;Testing;Automation</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/UI-Testing-Toolbox</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/UI-Testing-Toolbox</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore" Version="2.1.0" />
    <PackageReference Include="OrchardCore.Email.Abstractions" Version="2.1.0" />
    <PackageReference Include="OrchardCore.Liquid" Version="2.1.0" />
  </ItemGroup>

</Project>
