name: Publish to NuGet

on:
  push:

jobs:
  call-publish-workflow:
    uses: Lombiq/GitHub-Actions/.github/workflows/publish-nuget.yml@issue/OSOE-176
    secrets:
      API_KEY: ${{ secrets.DEFAULT_NUGET_PUBLISH_API_KEY }}
