<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Lombiq UI Testing Toolbox - Admin Theme</Title>
    <Authors>Lombiq Technologies</Authors>
    <Copyright>Copyright © 2020, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq UI Testing Toolbox - Admin Theme: Adjustments for the stock Orchard Core admin theme to make it more automation-friendly.</Description>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Selenium;Atata;Shouldly;xUnit;Axe;AccessibilityTesting;UITesting;Testing;Automation</PackageTags>
    <PackageIcon>NuGetIcon.png</PackageIcon>
    <RepositoryUrl>https://github.com/Lombiq/UI-Testing-Toolbox</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/UI-Testing-Toolbox/tree/dev/Lombiq.Tests.UI.AdminTheme</PackageProjectUrl>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="NuGetIcon.png" Pack="true" PackagePath="" />
    <None Include="..\Readme.md" Link="Readme.md" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Theme.Targets" Version="3.0.0-preview-18984"/>
    <PackageReference Include="OrchardCore.ContentManagement" Version="3.0.0-preview-18984"/>
    <PackageReference Include="OrchardCore.DisplayManagement" Version="3.0.0-preview-18984"/>
    <PackageReference Include="OrchardCore.ResourceManagement" Version="3.0.0-preview-18984"/>
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' != 'true'">
    <ProjectReference Include="..\..\..\src\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.OrchardCore\Lombiq.HelpfulLibraries.OrchardCore.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.HelpfulLibraries.OrchardCore" Version="12.6.1-alpha.7.osoe-925" />
  </ItemGroup>

</Project>
